name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libncurses-dev
      run: sudo apt update && sudo apt-get install libncurses-dev
    - name: make
      run: make
